import {
  type Organization,
  type Workspace,
  type Department,
  type User,
  type Agent,
  type AgentPermission,
  type Project,
  type Task,
  type TaskDependency,
  type TaskRun,
  type Approval,
  type LogEvent,
  type Notification,
  type MemoryEntry,
  type SOPDocument,
  type PromptTemplate,
  type Artifact,
  type Integration,
  type CostRecord,
  type AgentHeartbeat,
  type Comment,
  type ModuleInstallation,
  type Listing,
  type MediaAsset,
  type PostDraft,
  type PublishedPost,
  type ShareTask,
  type InvoiceSnapshot,
  type IntegrationAccount,
  WorkspaceType,
  UserRole,
  AgentStatus,
  Visibility,
  ProjectStatus,
  TaskStatus,
  TaskPriority,
  TaskRunStatus,
  ApprovalStatus,
  Severity,
  MemoryType,
  ArtifactType,
  IntegrationType,
  IntegrationStatus,
  LogLevel,
  ListingStatus,
  MediaAssetType,
  PostDraftStatus,
  PostPlatform,
  ShareTaskStatus,
  InvoiceStatus,
  ModuleStatus,
} from "./types";

// ─── Helpers ─────────────────────────────────────────────────────────────────

function daysAgo(n: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d;
}

function hoursAgo(n: number): Date {
  const d = new Date();
  d.setHours(d.getHours() - n);
  return d;
}

function minutesAgo(n: number): Date {
  const d = new Date();
  d.setMinutes(d.getMinutes() - n);
  return d;
}

function daysFromNow(n: number): Date {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d;
}

// ─── Organization ────────────────────────────────────────────────────────────

export const organization: Organization = {
  id: "org-1",
  name: "Trung AI Ops",
  slug: "trung-ai-ops",
  logoUrl: "/logos/trung-ai-ops.svg",
  plan: "enterprise",
  createdAt: daysAgo(120),
  updatedAt: daysAgo(2),
};

// ─── Workspaces ──────────────────────────────────────────────────────────────

export const workspaces: Workspace[] = [
  {
    id: "ws-hq",
    organizationId: "org-1",
    name: "HQ",
    slug: "hq",
    type: WorkspaceType.HQ,
    description: "Central command — internal operations, engineering, and strategy",
    createdAt: daysAgo(120),
    updatedAt: daysAgo(5),
  },
  {
    id: "ws-bros",
    organizationId: "org-1",
    name: "Bros Photo",
    slug: "bros-photo",
    type: WorkspaceType.CLIENT,
    description: "Real-estate photography & content production for Bros Photo Houston",
    iconUrl: "/logos/bros-photo.png",
    createdAt: daysAgo(60),
    updatedAt: daysAgo(1),
  },
  {
    id: "ws-luxe",
    organizationId: "org-1",
    name: "Luxe Realty Group",
    slug: "luxe-realty",
    type: WorkspaceType.CLIENT,
    description: "Full-service marketing & social media for Luxe Realty Group",
    iconUrl: "/logos/luxe-realty.png",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
];

// ─── Departments ─────────────────────────────────────────────────────────────

export const departments: Department[] = [
  // HQ
  { id: "dept-hq-mkt", workspaceId: "ws-hq", name: "Marketing", description: "Brand strategy and growth", createdAt: daysAgo(120), updatedAt: daysAgo(10) },
  { id: "dept-hq-eng", workspaceId: "ws-hq", name: "Engineering", description: "Platform dev, infra, and automation", createdAt: daysAgo(120), updatedAt: daysAgo(10) },
  { id: "dept-hq-ops", workspaceId: "ws-hq", name: "Operations", description: "Day-to-day business operations", createdAt: daysAgo(120), updatedAt: daysAgo(10) },
  { id: "dept-hq-fin", workspaceId: "ws-hq", name: "Finance", description: "Billing, invoicing, and cost tracking", createdAt: daysAgo(120), updatedAt: daysAgo(10) },
  // Bros Photo
  { id: "dept-bros-content", workspaceId: "ws-bros", name: "Content", description: "Listing copy, captions, and blog posts", createdAt: daysAgo(60), updatedAt: daysAgo(5) },
  { id: "dept-bros-listing", workspaceId: "ws-bros", name: "Listing Ops", description: "Photo intake, media QA, and delivery", createdAt: daysAgo(60), updatedAt: daysAgo(5) },
  { id: "dept-bros-client", workspaceId: "ws-bros", name: "Client Ops", description: "Scheduling, invoicing, and client comms", createdAt: daysAgo(60), updatedAt: daysAgo(5) },
  // Luxe Realty
  { id: "dept-luxe-mkt", workspaceId: "ws-luxe", name: "Marketing", description: "Social media and digital marketing", createdAt: daysAgo(30), updatedAt: daysAgo(3) },
  { id: "dept-luxe-sales", workspaceId: "ws-luxe", name: "Sales", description: "Lead gen and follow-up automation", createdAt: daysAgo(30), updatedAt: daysAgo(3) },
  { id: "dept-luxe-admin", workspaceId: "ws-luxe", name: "Admin", description: "Administrative tasks and coordination", createdAt: daysAgo(30), updatedAt: daysAgo(3) },
];

// ─── Users ───────────────────────────────────────────────────────────────────

export const users: User[] = [
  {
    id: "user-trung",
    organizationId: "org-1",
    email: "trung@trungaiops.com",
    name: "Trung Do",
    avatarUrl: "/avatars/trung.jpg",
    role: UserRole.OWNER,
    workspaceIds: ["ws-hq", "ws-bros", "ws-luxe"],
    createdAt: daysAgo(120),
    updatedAt: daysAgo(1),
  },
  {
    id: "user-maria",
    organizationId: "org-1",
    email: "maria@trungaiops.com",
    name: "Maria Nguyen",
    avatarUrl: "/avatars/maria.jpg",
    role: UserRole.ADMIN,
    workspaceIds: ["ws-hq", "ws-bros"],
    createdAt: daysAgo(90),
    updatedAt: daysAgo(3),
  },
  {
    id: "user-derek",
    organizationId: "org-1",
    email: "derek@trungaiops.com",
    name: "Derek Pham",
    role: UserRole.MANAGER,
    workspaceIds: ["ws-bros", "ws-luxe"],
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: "user-jessica",
    organizationId: "org-1",
    email: "jessica@trungaiops.com",
    name: "Jessica Torres",
    role: UserRole.MEMBER,
    workspaceIds: ["ws-luxe"],
    createdAt: daysAgo(25),
    updatedAt: daysAgo(1),
  },
];

// ─── Agents ──────────────────────────────────────────────────────────────────

export const agents: Agent[] = [
  {
    id: "agent-lil-bin",
    organizationId: "org-1",
    name: "lil_Bin",
    slug: "lil-bin",
    description: "Chief of Staff AI — orchestrates agents, triages tasks, and manages the operating rhythm across all workspaces",
    status: AgentStatus.BUSY,
    model: "gpt-4o",
    provider: "openai",
    systemPrompt: "You are lil_Bin, the Chief of Staff AI for Trung AI Ops. You oversee all agent operations, triage incoming tasks, and ensure nothing falls through the cracks.",
    visibility: Visibility.GLOBAL,
    capabilities: ["task-triage", "agent-orchestration", "reporting", "notifications", "sop-enforcement"],
    tags: ["core", "orchestrator", "org-level"],
    createdById: "user-trung",
    lastActiveAt: minutesAgo(2),
    createdAt: daysAgo(120),
    updatedAt: daysAgo(1),
  },
  {
    id: "agent-scribe",
    organizationId: "org-1",
    workspaceId: "ws-bros",
    departmentId: "dept-bros-content",
    name: "Scribe",
    slug: "scribe",
    description: "Content Writer — generates listing descriptions, blog posts, and marketing copy for real-estate clients",
    status: AgentStatus.ONLINE,
    model: "claude-sonnet-4-20250514",
    provider: "anthropic",
    visibility: Visibility.WORKSPACE,
    capabilities: ["listing-description", "blog-writing", "caption-generation", "seo-optimization"],
    tags: ["content", "writing", "real-estate"],
    createdById: "user-trung",
    lastActiveAt: minutesAgo(15),
    createdAt: daysAgo(58),
    updatedAt: daysAgo(1),
  },
  {
    id: "agent-pixel",
    organizationId: "org-1",
    workspaceId: "ws-bros",
    departmentId: "dept-bros-listing",
    name: "Pixel",
    slug: "pixel",
    description: "Listing Coordinator — manages photo intake, organizes media assets, and tracks listing status through the pipeline",
    status: AgentStatus.IDLE,
    model: "gpt-4o-mini",
    provider: "openai",
    visibility: Visibility.WORKSPACE,
    capabilities: ["media-intake", "listing-tracking", "quality-check", "file-organization"],
    tags: ["listing", "media", "coordinator"],
    createdById: "user-trung",
    lastActiveAt: hoursAgo(1),
    createdAt: daysAgo(55),
    updatedAt: daysAgo(2),
  },
  {
    id: "agent-hype",
    organizationId: "org-1",
    workspaceId: "ws-bros",
    departmentId: "dept-bros-content",
    name: "Hype",
    slug: "hype",
    description: "Social Media Manager — creates post drafts, schedules content across platforms, and tracks engagement",
    status: AgentStatus.ONLINE,
    model: "gpt-4o",
    provider: "openai",
    visibility: Visibility.WORKSPACE,
    capabilities: ["social-posting", "caption-writing", "hashtag-research", "scheduling", "analytics"],
    tags: ["social-media", "content", "scheduling"],
    createdById: "user-trung",
    lastActiveAt: minutesAgo(30),
    createdAt: daysAgo(50),
    updatedAt: daysAgo(1),
  },
  {
    id: "agent-ledger",
    organizationId: "org-1",
    workspaceId: "ws-hq",
    departmentId: "dept-hq-fin",
    name: "Ledger",
    slug: "ledger",
    description: "Invoice Tracker — monitors overdue invoices, generates payment reminders, and syncs with Stripe",
    status: AgentStatus.ONLINE,
    model: "gpt-4o-mini",
    provider: "openai",
    visibility: Visibility.GLOBAL,
    capabilities: ["invoice-tracking", "payment-reminders", "stripe-sync", "overdue-detection"],
    tags: ["finance", "invoicing", "payments"],
    createdById: "user-trung",
    lastActiveAt: hoursAgo(2),
    createdAt: daysAgo(100),
    updatedAt: daysAgo(1),
  },
  {
    id: "agent-compass",
    organizationId: "org-1",
    workspaceId: "ws-luxe",
    departmentId: "dept-luxe-mkt",
    name: "Compass",
    slug: "compass",
    description: "Marketing Strategist — builds campaign plans, analyzes market trends, and optimizes ad spend for Luxe Realty",
    status: AgentStatus.IDLE,
    model: "claude-sonnet-4-20250514",
    provider: "anthropic",
    visibility: Visibility.WORKSPACE,
    capabilities: ["campaign-planning", "market-analysis", "ad-optimization", "competitor-tracking"],
    tags: ["marketing", "strategy", "analytics"],
    createdById: "user-trung",
    lastActiveAt: hoursAgo(4),
    createdAt: daysAgo(28),
    updatedAt: daysAgo(2),
  },
  {
    id: "agent-echo",
    organizationId: "org-1",
    workspaceId: "ws-luxe",
    departmentId: "dept-luxe-mkt",
    name: "Echo",
    slug: "echo",
    description: "Social Media Manager — manages Luxe Realty's social presence across Facebook, Instagram, and TikTok",
    status: AgentStatus.BUSY,
    model: "gpt-4o",
    provider: "openai",
    visibility: Visibility.WORKSPACE,
    capabilities: ["social-posting", "content-calendar", "engagement-tracking", "cross-posting"],
    tags: ["social-media", "luxe-realty"],
    createdById: "user-trung",
    lastActiveAt: minutesAgo(5),
    createdAt: daysAgo(26),
    updatedAt: daysAgo(1),
  },
  {
    id: "agent-atlas",
    organizationId: "org-1",
    workspaceId: "ws-hq",
    departmentId: "dept-hq-ops",
    name: "Atlas",
    slug: "atlas",
    description: "Data Analyst — aggregates metrics, generates operational reports, and surfaces cost anomalies",
    status: AgentStatus.ONLINE,
    model: "gpt-4o",
    provider: "openai",
    visibility: Visibility.GLOBAL,
    capabilities: ["data-aggregation", "report-generation", "anomaly-detection", "dashboard-updates"],
    tags: ["analytics", "reporting", "data"],
    createdById: "user-trung",
    lastActiveAt: hoursAgo(1),
    createdAt: daysAgo(90),
    updatedAt: daysAgo(1),
  },
  {
    id: "agent-forge",
    organizationId: "org-1",
    workspaceId: "ws-hq",
    departmentId: "dept-hq-eng",
    name: "Forge",
    slug: "forge",
    description: "Engineering & Automation — builds pipelines, maintains integrations, and deploys workflow automations",
    status: AgentStatus.PAUSED,
    model: "claude-sonnet-4-20250514",
    provider: "anthropic",
    visibility: Visibility.GLOBAL,
    capabilities: ["pipeline-building", "integration-maintenance", "deployment", "code-generation"],
    tags: ["engineering", "automation", "devops"],
    createdById: "user-trung",
    lastActiveAt: hoursAgo(6),
    createdAt: daysAgo(110),
    updatedAt: daysAgo(3),
  },
  {
    id: "agent-nova",
    organizationId: "org-1",
    workspaceId: "ws-bros",
    departmentId: "dept-bros-content",
    name: "Nova",
    slug: "nova",
    description: "Content Writer — specializes in luxury-market property descriptions and neighborhood spotlights",
    status: AgentStatus.OFFLINE,
    model: "claude-sonnet-4-20250514",
    provider: "anthropic",
    visibility: Visibility.WORKSPACE,
    capabilities: ["luxury-copy", "neighborhood-spotlights", "property-highlights"],
    tags: ["content", "luxury", "writing"],
    createdById: "user-maria",
    lastActiveAt: daysAgo(1),
    createdAt: daysAgo(40),
    updatedAt: daysAgo(1),
  },
  {
    id: "agent-radar",
    organizationId: "org-1",
    workspaceId: "ws-luxe",
    departmentId: "dept-luxe-sales",
    name: "Radar",
    slug: "radar",
    description: "Lead Analyst — scores incoming leads, tracks follow-ups, and alerts the sales team on hot prospects",
    status: AgentStatus.ONLINE,
    model: "gpt-4o-mini",
    provider: "openai",
    visibility: Visibility.WORKSPACE,
    capabilities: ["lead-scoring", "follow-up-tracking", "crm-sync", "alert-dispatch"],
    tags: ["sales", "leads", "analytics"],
    createdById: "user-trung",
    lastActiveAt: hoursAgo(3),
    createdAt: daysAgo(25),
    updatedAt: daysAgo(1),
  },
  {
    id: "agent-quill",
    organizationId: "org-1",
    workspaceId: "ws-hq",
    departmentId: "dept-hq-mkt",
    name: "Quill",
    slug: "quill",
    description: "Brand Copywriter — maintains brand voice across all workspaces, writes newsletters and marketing materials",
    status: AgentStatus.IDLE,
    model: "gpt-4o",
    provider: "openai",
    visibility: Visibility.GLOBAL,
    capabilities: ["brand-voice", "newsletter", "marketing-copy", "style-guide-enforcement"],
    tags: ["marketing", "brand", "writing"],
    createdById: "user-trung",
    lastActiveAt: hoursAgo(5),
    createdAt: daysAgo(80),
    updatedAt: daysAgo(2),
  },
  {
    id: "agent-sentinel",
    organizationId: "org-1",
    workspaceId: "ws-hq",
    departmentId: "dept-hq-eng",
    name: "Sentinel",
    slug: "sentinel",
    description: "System Monitor — watches agent health, tracks heartbeats, and escalates errors to lil_Bin",
    status: AgentStatus.ONLINE,
    model: "gpt-4o-mini",
    provider: "openai",
    visibility: Visibility.GLOBAL,
    capabilities: ["health-monitoring", "heartbeat-tracking", "error-escalation", "uptime-reporting"],
    tags: ["monitoring", "infrastructure", "alerts"],
    createdById: "user-trung",
    lastActiveAt: minutesAgo(1),
    createdAt: daysAgo(100),
    updatedAt: daysAgo(1),
  },
  {
    id: "agent-muse",
    organizationId: "org-1",
    workspaceId: "ws-bros",
    departmentId: "dept-bros-client",
    name: "Muse",
    slug: "muse",
    description: "Client Ops Assistant — handles scheduling, sends shoot confirmations, and manages client communications",
    status: AgentStatus.ERROR,
    model: "gpt-4o-mini",
    provider: "openai",
    visibility: Visibility.WORKSPACE,
    capabilities: ["scheduling", "email-drafts", "client-comms", "calendar-sync"],
    tags: ["client-ops", "scheduling", "communications"],
    createdById: "user-derek",
    lastActiveAt: hoursAgo(8),
    createdAt: daysAgo(35),
    updatedAt: hoursAgo(8),
  },
];

// ─── Agent Permissions ───────────────────────────────────────────────────────

export const agentPermissions: AgentPermission[] = [
  { id: "perm-1", agentId: "agent-lil-bin", workspaceId: "ws-hq", canRead: true, canWrite: true, canExecute: true, canApprove: false, grantedById: "user-trung", createdAt: daysAgo(120), updatedAt: daysAgo(5) },
  { id: "perm-2", agentId: "agent-lil-bin", workspaceId: "ws-bros", canRead: true, canWrite: true, canExecute: true, canApprove: false, grantedById: "user-trung", createdAt: daysAgo(60), updatedAt: daysAgo(5) },
  { id: "perm-3", agentId: "agent-lil-bin", workspaceId: "ws-luxe", canRead: true, canWrite: true, canExecute: true, canApprove: false, grantedById: "user-trung", createdAt: daysAgo(30), updatedAt: daysAgo(5) },
  { id: "perm-4", agentId: "agent-scribe", workspaceId: "ws-bros", canRead: true, canWrite: true, canExecute: true, canApprove: false, grantedById: "user-trung", createdAt: daysAgo(58), updatedAt: daysAgo(5) },
  { id: "perm-5", agentId: "agent-ledger", workspaceId: "ws-hq", canRead: true, canWrite: true, canExecute: true, canApprove: false, grantedById: "user-trung", createdAt: daysAgo(100), updatedAt: daysAgo(5) },
  { id: "perm-6", agentId: "agent-ledger", workspaceId: "ws-bros", canRead: true, canWrite: false, canExecute: false, canApprove: false, grantedById: "user-trung", createdAt: daysAgo(60), updatedAt: daysAgo(5) },
];

// ─── Projects ────────────────────────────────────────────────────────────────

export const projects: Project[] = [
  {
    id: "proj-q1-content",
    workspaceId: "ws-bros",
    name: "Q1 Content Pipeline",
    description: "Build out the full listing-to-post content pipeline for Bros Photo's Q1 listings",
    status: ProjectStatus.ACTIVE,
    ownerId: "user-trung",
    startDate: daysAgo(25),
    endDate: daysFromNow(5),
    createdAt: daysAgo(25),
    updatedAt: daysAgo(1),
  },
  {
    id: "proj-website",
    workspaceId: "ws-hq",
    name: "Website Redesign",
    description: "Rebuild the Trung AI Ops marketing site with new dashboard previews and agent profiles",
    status: ProjectStatus.ACTIVE,
    ownerId: "user-maria",
    startDate: daysAgo(20),
    endDate: daysFromNow(25),
    createdAt: daysAgo(20),
    updatedAt: daysAgo(2),
  },
  {
    id: "proj-invoice-auto",
    workspaceId: "ws-hq",
    name: "Invoice Automation",
    description: "Automate invoice generation, reminders, and Stripe reconciliation across all client workspaces",
    status: ProjectStatus.ACTIVE,
    ownerId: "user-trung",
    startDate: daysAgo(15),
    endDate: daysFromNow(15),
    createdAt: daysAgo(15),
    updatedAt: daysAgo(1),
  },
  {
    id: "proj-bros-launch",
    workspaceId: "ws-bros",
    name: "Bros Photo Launch",
    description: "Complete onboarding, agent setup, and first batch of listings for the Bros Photo workspace",
    status: ProjectStatus.COMPLETED,
    ownerId: "user-derek",
    startDate: daysAgo(55),
    endDate: daysAgo(10),
    createdAt: daysAgo(55),
    updatedAt: daysAgo(10),
  },
  {
    id: "proj-luxe-onboard",
    workspaceId: "ws-luxe",
    name: "Luxe Realty Onboarding",
    description: "Set up agents, integrations, and initial campaigns for Luxe Realty Group",
    status: ProjectStatus.ACTIVE,
    ownerId: "user-trung",
    startDate: daysAgo(28),
    endDate: daysFromNow(10),
    createdAt: daysAgo(28),
    updatedAt: daysAgo(1),
  },
  {
    id: "proj-social-q1",
    workspaceId: "ws-luxe",
    name: "Q1 Social Media Blitz",
    description: "Execute a high-frequency social campaign across Facebook, Instagram, and TikTok for Luxe Realty",
    status: ProjectStatus.ACTIVE,
    ownerId: "user-jessica",
    startDate: daysAgo(14),
    endDate: daysFromNow(16),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(1),
  },
  {
    id: "proj-monitoring",
    workspaceId: "ws-hq",
    name: "Agent Monitoring v2",
    description: "Upgrade the heartbeat and health-check system with anomaly detection and auto-restart",
    status: ProjectStatus.PAUSED,
    ownerId: "user-maria",
    startDate: daysAgo(18),
    createdAt: daysAgo(18),
    updatedAt: daysAgo(5),
  },
];

// ─── Tasks ───────────────────────────────────────────────────────────────────

export const tasks: Task[] = [
  // Bros Photo — Content Pipeline
  {
    id: "task-1",
    workspaceId: "ws-bros",
    projectId: "proj-q1-content",
    agentId: "agent-scribe",
    title: "Generate listing description for 1234 Oak St",
    description: "Write a compelling MLS-ready description for the 4BR/3BA home at 1234 Oak St, Houston Heights. Highlight the renovated kitchen and backyard pool.",
    status: TaskStatus.COMPLETED,
    priority: TaskPriority.HIGH,
    dueDate: daysAgo(2),
    tags: ["listing", "content", "heights"],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
  },
  {
    id: "task-2",
    workspaceId: "ws-bros",
    projectId: "proj-q1-content",
    agentId: "agent-scribe",
    title: "Generate listing description for 5678 Westheimer Rd",
    description: "Create listing copy for the 2BR/2BA condo at 5678 Westheimer Rd. Emphasize proximity to the Galleria and modern finishes.",
    status: TaskStatus.RUNNING,
    priority: TaskPriority.MEDIUM,
    dueDate: daysFromNow(1),
    tags: ["listing", "content", "galleria"],
    createdAt: daysAgo(3),
    updatedAt: minutesAgo(20),
  },
  {
    id: "task-3",
    workspaceId: "ws-bros",
    projectId: "proj-q1-content",
    agentId: "agent-hype",
    title: "Create Instagram carousel for 1234 Oak St listing",
    description: "Design a 5-slide Instagram carousel with captions for the Oak St listing. Use brand-approved templates.",
    status: TaskStatus.QUEUED,
    priority: TaskPriority.MEDIUM,
    dueDate: daysFromNow(2),
    tags: ["social-media", "instagram", "carousel"],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: "task-4",
    workspaceId: "ws-bros",
    projectId: "proj-q1-content",
    agentId: "agent-pixel",
    title: "QA media assets for 9012 Memorial Dr",
    description: "Review 42 photos + 1 drone video uploaded for 9012 Memorial Dr. Flag any blurry or poorly-lit shots.",
    status: TaskStatus.COMPLETED,
    priority: TaskPriority.HIGH,
    tags: ["media", "qa", "memorial"],
    createdAt: daysAgo(6),
    updatedAt: daysAgo(4),
  },
  {
    id: "task-5",
    workspaceId: "ws-bros",
    projectId: "proj-q1-content",
    agentId: "agent-pixel",
    title: "Organize and tag photos for 3456 Montrose Blvd",
    description: "Sort 28 uploaded images into front exterior, interior rooms, and backyard. Apply EXIF-based tags.",
    status: TaskStatus.RUNNING,
    priority: TaskPriority.LOW,
    tags: ["media", "organization"],
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(3),
  },
  {
    id: "task-6",
    workspaceId: "ws-bros",
    agentId: "agent-nova",
    title: "Write neighborhood spotlight: Houston Heights",
    description: "Draft a 600-word neighborhood guide for Houston Heights covering walkability, schools, dining, and market trends.",
    status: TaskStatus.BACKLOG,
    priority: TaskPriority.LOW,
    tags: ["content", "neighborhood", "blog"],
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  // Bros Photo — Client Ops
  {
    id: "task-7",
    workspaceId: "ws-bros",
    agentId: "agent-muse",
    title: "Send shoot confirmation to client: Remax Heights",
    description: "Draft and send a confirmation email for the March 22 shoot at 7890 Yale St. Include parking instructions.",
    status: TaskStatus.FAILED,
    priority: TaskPriority.HIGH,
    dueDate: daysAgo(1),
    tags: ["client-ops", "email", "scheduling"],
    metadata: { errorReason: "SMTP connection timeout — email provider rate-limited" },
    createdAt: daysAgo(3),
    updatedAt: hoursAgo(8),
  },
  {
    id: "task-8",
    workspaceId: "ws-bros",
    agentId: "agent-ledger",
    title: "Process overdue invoices for Bros Photo",
    description: "Identify all invoices past due by 15+ days, generate reminder emails, and flag for Trung's review.",
    status: TaskStatus.AWAITING_APPROVAL,
    priority: TaskPriority.CRITICAL,
    dueDate: daysAgo(1),
    tags: ["finance", "invoicing", "overdue"],
    createdAt: daysAgo(4),
    updatedAt: hoursAgo(2),
  },
  // Luxe Realty — Social & Marketing
  {
    id: "task-9",
    workspaceId: "ws-luxe",
    projectId: "proj-social-q1",
    agentId: "agent-echo",
    title: "Draft Facebook post for 2200 River Oaks Blvd listing",
    description: "Write an engagement-optimized Facebook post for the luxury listing at 2200 River Oaks Blvd. Include virtual tour link.",
    status: TaskStatus.RUNNING,
    priority: TaskPriority.HIGH,
    dueDate: daysFromNow(1),
    tags: ["social-media", "facebook", "luxury"],
    createdAt: daysAgo(2),
    updatedAt: minutesAgo(5),
  },
  {
    id: "task-10",
    workspaceId: "ws-luxe",
    projectId: "proj-social-q1",
    agentId: "agent-echo",
    title: "Schedule TikTok video series: 'Dream Homes of River Oaks'",
    description: "Plan and schedule a 5-part TikTok series showcasing luxury properties in River Oaks. Each video under 60 seconds.",
    status: TaskStatus.QUEUED,
    priority: TaskPriority.MEDIUM,
    dueDate: daysFromNow(5),
    tags: ["social-media", "tiktok", "video"],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: "task-11",
    workspaceId: "ws-luxe",
    projectId: "proj-social-q1",
    agentId: "agent-compass",
    title: "Review social media calendar Q1",
    description: "Audit the current Q1 social calendar for Luxe Realty. Check posting frequency, platform balance, and content gaps.",
    status: TaskStatus.COMPLETED,
    priority: TaskPriority.MEDIUM,
    tags: ["marketing", "audit", "calendar"],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(7),
  },
  {
    id: "task-12",
    workspaceId: "ws-luxe",
    projectId: "proj-luxe-onboard",
    agentId: "agent-compass",
    title: "Build competitor analysis for Keller Williams Midtown",
    description: "Research KW Midtown's social media presence, ad spend estimates, and content strategy. Deliver a 2-page brief.",
    status: TaskStatus.BLOCKED,
    priority: TaskPriority.MEDIUM,
    tags: ["marketing", "competitor", "research"],
    metadata: { blockedReason: "Waiting for Meta Ads API integration to go live" },
    createdAt: daysAgo(8),
    updatedAt: daysAgo(3),
  },
  {
    id: "task-13",
    workspaceId: "ws-luxe",
    projectId: "proj-luxe-onboard",
    agentId: "agent-radar",
    title: "Import lead list from Luxe Realty CRM export",
    description: "Parse the CSV export from Luxe's legacy CRM (482 contacts), deduplicate, and load into the workspace.",
    status: TaskStatus.COMPLETED,
    priority: TaskPriority.HIGH,
    tags: ["sales", "leads", "import"],
    createdAt: daysAgo(20),
    updatedAt: daysAgo(18),
  },
  // HQ — Engineering & Ops
  {
    id: "task-14",
    workspaceId: "ws-hq",
    projectId: "proj-invoice-auto",
    agentId: "agent-forge",
    title: "Deploy automation pipeline v2",
    description: "Ship the updated invoice-generation pipeline with Stripe webhook handling and retry logic.",
    status: TaskStatus.QUEUED,
    priority: TaskPriority.CRITICAL,
    dueDate: daysFromNow(3),
    tags: ["engineering", "deployment", "invoicing"],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
  {
    id: "task-15",
    workspaceId: "ws-hq",
    projectId: "proj-invoice-auto",
    agentId: "agent-forge",
    title: "Fix Stripe webhook signature validation bug",
    description: "The webhook endpoint is rejecting valid Stripe events due to a clock-skew tolerance issue. Investigate and patch.",
    status: TaskStatus.COMPLETED,
    priority: TaskPriority.CRITICAL,
    tags: ["engineering", "bugfix", "stripe"],
    createdAt: daysAgo(7),
    updatedAt: daysAgo(4),
  },
  {
    id: "task-16",
    workspaceId: "ws-hq",
    projectId: "proj-website",
    agentId: "agent-quill",
    title: "Write hero copy for new landing page",
    description: "Draft 3 headline/sub-headline variants for the redesigned Trung AI Ops landing page. Focus on 'AI workforce' messaging.",
    status: TaskStatus.AWAITING_APPROVAL,
    priority: TaskPriority.HIGH,
    tags: ["marketing", "website", "copy"],
    createdAt: daysAgo(6),
    updatedAt: daysAgo(2),
  },
  {
    id: "task-17",
    workspaceId: "ws-hq",
    projectId: "proj-monitoring",
    agentId: "agent-sentinel",
    title: "Implement anomaly detection for agent heartbeats",
    description: "Add statistical anomaly detection to the heartbeat stream. Alert when an agent's response time deviates >2σ from its rolling average.",
    status: TaskStatus.BACKLOG,
    priority: TaskPriority.MEDIUM,
    tags: ["engineering", "monitoring", "anomaly"],
    createdAt: daysAgo(12),
    updatedAt: daysAgo(5),
  },
  {
    id: "task-18",
    workspaceId: "ws-hq",
    agentId: "agent-atlas",
    title: "Generate weekly ops report (Mar 10–16)",
    description: "Compile task completion rates, agent uptime, cost breakdowns, and key events for the weekly ops digest.",
    status: TaskStatus.COMPLETED,
    priority: TaskPriority.MEDIUM,
    tags: ["reporting", "ops", "weekly"],
    createdAt: daysAgo(6),
    updatedAt: daysAgo(4),
  },
  {
    id: "task-19",
    workspaceId: "ws-hq",
    agentId: "agent-atlas",
    title: "Generate weekly ops report (Mar 17–23)",
    description: "Compile task completion rates, agent uptime, cost breakdowns, and key events for the weekly ops digest.",
    status: TaskStatus.RUNNING,
    priority: TaskPriority.MEDIUM,
    dueDate: daysFromNow(1),
    tags: ["reporting", "ops", "weekly"],
    createdAt: daysAgo(1),
    updatedAt: minutesAgo(45),
  },
  {
    id: "task-20",
    workspaceId: "ws-hq",
    agentId: "agent-lil-bin",
    title: "Triage incoming tasks and assign agents",
    description: "Review the backlog queue, auto-assign tasks to available agents based on capability match, and escalate blockers.",
    status: TaskStatus.RUNNING,
    priority: TaskPriority.HIGH,
    tags: ["orchestration", "triage", "daily"],
    createdAt: hoursAgo(1),
    updatedAt: minutesAgo(10),
  },
  {
    id: "task-21",
    workspaceId: "ws-bros",
    projectId: "proj-q1-content",
    agentId: "agent-scribe",
    title: "Generate listing description for 4500 Kirby Dr #12",
    description: "Write listing copy for the 1BR/1BA luxury high-rise unit at 4500 Kirby Dr. Highlight skyline views and concierge.",
    status: TaskStatus.BACKLOG,
    priority: TaskPriority.MEDIUM,
    tags: ["listing", "content", "high-rise"],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "task-22",
    workspaceId: "ws-luxe",
    projectId: "proj-social-q1",
    agentId: "agent-echo",
    title: "Post weekly market update to Facebook Page",
    description: "Publish the weekly Houston luxury market stats (median price, days-on-market, inventory) as a branded graphic post.",
    status: TaskStatus.COMPLETED,
    priority: TaskPriority.MEDIUM,
    tags: ["social-media", "facebook", "market-update"],
    createdAt: daysAgo(8),
    updatedAt: daysAgo(6),
  },
  {
    id: "task-23",
    workspaceId: "ws-bros",
    agentId: "agent-hype",
    title: "A/B test caption styles for Instagram Reels",
    description: "Create two caption variants (story-driven vs. stats-driven) for the next 5 Reels and track engagement rates.",
    status: TaskStatus.QUEUED,
    priority: TaskPriority.LOW,
    tags: ["social-media", "testing", "instagram"],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
  },
  {
    id: "task-24",
    workspaceId: "ws-hq",
    projectId: "proj-invoice-auto",
    agentId: "agent-ledger",
    title: "Reconcile February Stripe payouts",
    description: "Match all February Stripe payouts against issued invoices. Flag any discrepancies for manual review.",
    status: TaskStatus.COMPLETED,
    priority: TaskPriority.HIGH,
    tags: ["finance", "reconciliation", "stripe"],
    createdAt: daysAgo(12),
    updatedAt: daysAgo(9),
  },
  {
    id: "task-25",
    workspaceId: "ws-luxe",
    agentId: "agent-radar",
    title: "Score and prioritize March lead batch",
    description: "Run lead scoring on the 38 new leads received this week. Assign hot/warm/cold labels and notify sales team.",
    status: TaskStatus.RUNNING,
    priority: TaskPriority.HIGH,
    tags: ["sales", "lead-scoring", "weekly"],
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(4),
  },
  {
    id: "task-26",
    workspaceId: "ws-hq",
    agentId: "agent-lil-bin",
    title: "Prepare agent performance summary for Trung",
    description: "Compile agent task completion rates, error rates, and cost per task for all 14 agents over the past 7 days.",
    status: TaskStatus.QUEUED,
    priority: TaskPriority.HIGH,
    dueDate: daysFromNow(1),
    tags: ["reporting", "performance", "summary"],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "task-27",
    workspaceId: "ws-bros",
    projectId: "proj-q1-content",
    agentId: "agent-scribe",
    title: "Generate listing description for 7890 Yale St",
    description: "Write MLS-ready copy for the 3BR/2BA craftsman at 7890 Yale St. Emphasize the original hardwood floors and wrap-around porch.",
    status: TaskStatus.AWAITING_APPROVAL,
    priority: TaskPriority.MEDIUM,
    tags: ["listing", "content", "heights"],
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
  },
  {
    id: "task-28",
    workspaceId: "ws-hq",
    projectId: "proj-website",
    assignedToUserId: "user-maria",
    title: "Design agent profile card component",
    description: "Create a reusable UI component that displays an agent's name, status, model, and recent activity. Follow the design system.",
    status: TaskStatus.RUNNING,
    priority: TaskPriority.MEDIUM,
    tags: ["engineering", "ui", "design-system"],
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
  },
];

// ─── Task Dependencies ──────────────────────────────────────────────────────

export const taskDependencies: TaskDependency[] = [
  { id: "dep-1", taskId: "task-3", dependsOnTaskId: "task-1", createdAt: daysAgo(2) },
  { id: "dep-2", taskId: "task-14", dependsOnTaskId: "task-15", createdAt: daysAgo(5) },
];

// ─── Task Runs ───────────────────────────────────────────────────────────────

export const taskRuns: TaskRun[] = [
  { id: "run-1", taskId: "task-1", agentId: "agent-scribe", status: TaskRunStatus.COMPLETED, inputTokens: 1820, outputTokens: 890, costUsd: 0.042, durationMs: 12400, resultSummary: "Generated 280-word listing description with keyword optimization", startedAt: daysAgo(3), completedAt: daysAgo(3) },
  { id: "run-2", taskId: "task-4", agentId: "agent-pixel", status: TaskRunStatus.COMPLETED, inputTokens: 450, outputTokens: 320, costUsd: 0.008, durationMs: 45000, resultSummary: "Reviewed 42 photos, flagged 3 blurry shots (IMG_0034, IMG_0037, IMG_0041)", startedAt: daysAgo(5), completedAt: daysAgo(4) },
  { id: "run-3", taskId: "task-7", agentId: "agent-muse", status: TaskRunStatus.FAILED, inputTokens: 680, outputTokens: 240, costUsd: 0.009, durationMs: 8200, errorMessage: "SMTP connection timeout after 3 retries — provider rate limit exceeded", startedAt: hoursAgo(9), completedAt: hoursAgo(8) },
  { id: "run-4", taskId: "task-11", agentId: "agent-compass", status: TaskRunStatus.COMPLETED, inputTokens: 3200, outputTokens: 1450, costUsd: 0.072, durationMs: 28000, resultSummary: "Audited 47 scheduled posts across 3 platforms. Identified 2 content gaps and 1 platform imbalance.", startedAt: daysAgo(8), completedAt: daysAgo(7) },
  { id: "run-5", taskId: "task-13", agentId: "agent-radar", status: TaskRunStatus.COMPLETED, inputTokens: 2100, outputTokens: 380, costUsd: 0.025, durationMs: 18500, resultSummary: "Parsed 482 contacts, removed 63 duplicates, loaded 419 unique leads", startedAt: daysAgo(19), completedAt: daysAgo(18) },
  { id: "run-6", taskId: "task-15", agentId: "agent-forge", status: TaskRunStatus.COMPLETED, inputTokens: 4500, outputTokens: 1200, costUsd: 0.089, durationMs: 35000, resultSummary: "Patched clock-skew tolerance from 30s to 300s. Added test coverage for edge cases.", startedAt: daysAgo(5), completedAt: daysAgo(4) },
  { id: "run-7", taskId: "task-18", agentId: "agent-atlas", status: TaskRunStatus.COMPLETED, inputTokens: 5800, outputTokens: 2100, costUsd: 0.118, durationMs: 42000, resultSummary: "Generated 4-page ops report: 87% task completion, 99.2% uptime, $14.52 total cost", startedAt: daysAgo(5), completedAt: daysAgo(4) },
  { id: "run-8", taskId: "task-2", agentId: "agent-scribe", status: TaskRunStatus.RUNNING, inputTokens: 1650, outputTokens: 0, costUsd: 0.0, durationMs: 0, startedAt: minutesAgo(20) },
  { id: "run-9", taskId: "task-24", agentId: "agent-ledger", status: TaskRunStatus.COMPLETED, inputTokens: 3800, outputTokens: 900, costUsd: 0.047, durationMs: 22000, resultSummary: "Matched 34/36 payouts. 2 discrepancies flagged: INV-2024-0218 ($150 short), INV-2024-0231 (duplicate charge)", startedAt: daysAgo(10), completedAt: daysAgo(9) },
  { id: "run-10", taskId: "task-22", agentId: "agent-echo", status: TaskRunStatus.COMPLETED, inputTokens: 1200, outputTokens: 580, costUsd: 0.028, durationMs: 9500, resultSummary: "Published market update graphic to FB page. Reach: 1,240 in first 24h.", startedAt: daysAgo(7), completedAt: daysAgo(6) },
];

// ─── Approvals ───────────────────────────────────────────────────────────────

export const approvals: Approval[] = [
  {
    id: "appr-1",
    taskId: "task-8",
    requestedById: "agent-ledger",
    reviewerId: "user-trung",
    status: ApprovalStatus.PENDING,
    reason: "3 overdue invoices totaling $4,250 identified. Approval needed before sending reminder batch.",
    expiresAt: daysFromNow(2),
    createdAt: hoursAgo(2),
  },
  {
    id: "appr-2",
    taskId: "task-16",
    requestedById: "agent-quill",
    reviewerId: "user-trung",
    status: ApprovalStatus.PENDING,
    reason: "3 headline variants ready for review. Need sign-off before handoff to design team.",
    expiresAt: daysFromNow(3),
    createdAt: daysAgo(2),
  },
  {
    id: "appr-3",
    taskId: "task-27",
    requestedById: "agent-scribe",
    reviewerId: "user-derek",
    status: ApprovalStatus.PENDING,
    reason: "Listing description ready for client review before MLS submission.",
    expiresAt: daysFromNow(2),
    createdAt: daysAgo(1),
  },
  {
    id: "appr-4",
    taskId: "task-1",
    requestedById: "agent-scribe",
    reviewerId: "user-derek",
    status: ApprovalStatus.APPROVED,
    reason: "Listing description for 1234 Oak St — final review before MLS upload.",
    reviewNote: "Looks great. Minor tweak: change 'stunning' to 'beautifully renovated'. Approved with edit.",
    reviewedAt: daysAgo(2),
    createdAt: daysAgo(3),
  },
  {
    id: "appr-5",
    taskId: "task-15",
    requestedById: "agent-forge",
    reviewerId: "user-maria",
    status: ApprovalStatus.APPROVED,
    reason: "Stripe webhook fix ready for production deployment.",
    reviewNote: "Test coverage looks solid. Ship it.",
    reviewedAt: daysAgo(4),
    createdAt: daysAgo(5),
  },
  {
    id: "appr-6",
    taskId: "task-11",
    requestedById: "agent-compass",
    reviewerId: "user-jessica",
    status: ApprovalStatus.APPROVED,
    reason: "Q1 social calendar audit complete — recommended adjustments attached.",
    reviewNote: "Good catches on the content gaps. Let's add 2 more Reels per week.",
    reviewedAt: daysAgo(7),
    createdAt: daysAgo(8),
  },
  {
    id: "appr-7",
    taskId: "task-6",
    requestedById: "agent-lil-bin",
    reviewerId: "user-trung",
    status: ApprovalStatus.DENIED,
    reason: "Neighborhood spotlight proposed for Houston Heights — requesting content budget approval.",
    reviewNote: "Deprioritize for now. Focus on listing descriptions first — revisit in April.",
    reviewedAt: daysAgo(3),
    createdAt: daysAgo(4),
  },
];

// ─── Log Events ──────────────────────────────────────────────────────────────

export const logEvents: LogEvent[] = [
  { id: "log-1", organizationId: "org-1", workspaceId: "ws-hq", agentId: "agent-lil-bin", level: LogLevel.INFO, message: "Daily triage cycle started — 6 tasks in backlog", timestamp: minutesAgo(10) },
  { id: "log-2", organizationId: "org-1", workspaceId: "ws-bros", agentId: "agent-scribe", taskId: "task-2", level: LogLevel.INFO, message: "Started generating listing description for 5678 Westheimer Rd", timestamp: minutesAgo(20) },
  { id: "log-3", organizationId: "org-1", workspaceId: "ws-bros", agentId: "agent-muse", taskId: "task-7", level: LogLevel.ERROR, message: "SMTP connection timeout — email provider rate-limited after 3 retries", timestamp: hoursAgo(8) },
  { id: "log-4", organizationId: "org-1", workspaceId: "ws-hq", agentId: "agent-sentinel", level: LogLevel.WARN, message: "Agent 'Muse' heartbeat missed — last seen 8 hours ago", timestamp: hoursAgo(7) },
  { id: "log-5", organizationId: "org-1", workspaceId: "ws-luxe", agentId: "agent-echo", taskId: "task-9", level: LogLevel.INFO, message: "Drafting Facebook post for 2200 River Oaks Blvd — pulling listing data", timestamp: minutesAgo(5) },
  { id: "log-6", organizationId: "org-1", workspaceId: "ws-hq", agentId: "agent-atlas", taskId: "task-19", level: LogLevel.INFO, message: "Compiling weekly ops report — aggregating data from 3 workspaces", timestamp: minutesAgo(45) },
  { id: "log-7", organizationId: "org-1", workspaceId: "ws-hq", agentId: "agent-forge", level: LogLevel.INFO, message: "Pipeline v2 build #47 passed all tests — ready for deployment", timestamp: daysAgo(1) },
  { id: "log-8", organizationId: "org-1", workspaceId: "ws-luxe", agentId: "agent-radar", taskId: "task-25", level: LogLevel.INFO, message: "Lead scoring batch started — 38 leads to process", timestamp: hoursAgo(4) },
  { id: "log-9", organizationId: "org-1", agentId: "agent-lil-bin", level: LogLevel.WARN, message: "Agent 'Forge' has been paused for 6 hours — manual intervention may be needed", timestamp: hoursAgo(1) },
  { id: "log-10", organizationId: "org-1", workspaceId: "ws-bros", agentId: "agent-ledger", taskId: "task-8", level: LogLevel.INFO, message: "Identified 3 overdue invoices totaling $4,250 — awaiting approval to send reminders", timestamp: hoursAgo(2) },
  { id: "log-11", organizationId: "org-1", workspaceId: "ws-hq", agentId: "agent-sentinel", level: LogLevel.INFO, message: "All agents healthy — 12/14 online, 1 paused (Forge), 1 error (Muse)", timestamp: minutesAgo(1) },
  { id: "log-12", organizationId: "org-1", workspaceId: "ws-bros", agentId: "agent-pixel", taskId: "task-5", level: LogLevel.DEBUG, message: "Processing image batch — 12/28 photos tagged so far", timestamp: hoursAgo(3) },
  { id: "log-13", organizationId: "org-1", workspaceId: "ws-hq", agentId: "agent-quill", taskId: "task-16", level: LogLevel.INFO, message: "3 headline variants drafted — submitted for approval", timestamp: daysAgo(2) },
  { id: "log-14", organizationId: "org-1", workspaceId: "ws-luxe", agentId: "agent-compass", taskId: "task-12", level: LogLevel.WARN, message: "Task blocked — Meta Ads API integration not yet active", timestamp: daysAgo(3) },
  { id: "log-15", organizationId: "org-1", workspaceId: "ws-hq", agentId: "agent-forge", taskId: "task-15", level: LogLevel.INFO, message: "Stripe webhook fix deployed to production — monitoring for 24h", timestamp: daysAgo(4) },
  { id: "log-16", organizationId: "org-1", workspaceId: "ws-bros", agentId: "agent-hype", level: LogLevel.INFO, message: "Instagram carousel templates loaded — ready for task-3", timestamp: daysAgo(1) },
  { id: "log-17", organizationId: "org-1", agentId: "agent-lil-bin", level: LogLevel.CRITICAL, message: "Agent 'Muse' entered ERROR state — SMTP provider connection lost. Auto-retry exhausted.", timestamp: hoursAgo(8) },
  { id: "log-18", organizationId: "org-1", workspaceId: "ws-luxe", agentId: "agent-echo", taskId: "task-22", level: LogLevel.INFO, message: "Market update post published to Facebook — tracking engagement", timestamp: daysAgo(6) },
];

// ─── Notifications ───────────────────────────────────────────────────────────

export const notifications: Notification[] = [
  { id: "notif-1", userId: "user-trung", title: "Approval Required", message: "Ledger needs approval to send overdue invoice reminders for Bros Photo ($4,250 total)", severity: Severity.HIGH, isRead: false, linkUrl: "/approvals/appr-1", createdAt: hoursAgo(2) },
  { id: "notif-2", userId: "user-trung", title: "Agent Error", message: "Muse entered ERROR state — SMTP connection lost. Email tasks are stalled.", severity: Severity.CRITICAL, isRead: false, linkUrl: "/agents/agent-muse", createdAt: hoursAgo(8) },
  { id: "notif-3", userId: "user-trung", title: "Approval Required", message: "Quill submitted 3 headline variants for the landing page — ready for review", severity: Severity.MEDIUM, isRead: false, linkUrl: "/approvals/appr-2", createdAt: daysAgo(2) },
  { id: "notif-4", userId: "user-derek", title: "Approval Required", message: "Scribe's listing description for 7890 Yale St needs your review", severity: Severity.MEDIUM, isRead: false, linkUrl: "/approvals/appr-3", createdAt: daysAgo(1) },
  { id: "notif-5", userId: "user-trung", title: "Weekly Report Ready", message: "Atlas completed the ops report for Mar 10–16. Task completion: 87%, total cost: $14.52", severity: Severity.LOW, isRead: true, linkUrl: "/reports/run-7", createdAt: daysAgo(4) },
  { id: "notif-6", userId: "user-maria", title: "Deployment Ready", message: "Forge's Stripe webhook fix passed all tests and is ready for prod deployment", severity: Severity.MEDIUM, isRead: true, linkUrl: "/tasks/task-15", createdAt: daysAgo(4) },
  { id: "notif-7", userId: "user-jessica", title: "Calendar Audit Complete", message: "Compass finished the Q1 social calendar audit — 2 content gaps identified", severity: Severity.LOW, isRead: true, linkUrl: "/tasks/task-11", createdAt: daysAgo(7) },
  { id: "notif-8", userId: "user-trung", title: "Agent Paused", message: "Forge has been paused for 6+ hours — may need manual restart", severity: Severity.MEDIUM, isRead: false, linkUrl: "/agents/agent-forge", createdAt: hoursAgo(1) },
  { id: "notif-9", userId: "user-derek", title: "Invoice Alert", message: "Bros Photo has 3 overdue invoices — oldest is 22 days past due", severity: Severity.HIGH, isRead: false, linkUrl: "/invoices?workspace=ws-bros&status=overdue", createdAt: hoursAgo(2) },
  { id: "notif-10", userId: "user-trung", title: "Lead Scoring Complete", message: "Radar scored 38 new leads for Luxe Realty — 8 marked as hot", severity: Severity.LOW, isRead: false, linkUrl: "/tasks/task-25", createdAt: hoursAgo(4) },
];

// ─── Memory Entries ──────────────────────────────────────────────────────────

export const memoryEntries: MemoryEntry[] = [
  {
    id: "mem-1",
    organizationId: "org-1",
    type: MemoryType.INSTRUCTION,
    title: "Brand Voice Guidelines — Trung AI Ops",
    content: "Tone: confident, modern, slightly technical but accessible. Avoid jargon unless speaking to developers. Use 'AI workforce' instead of 'bots'. Always lead with the business outcome, not the technology.",
    tags: ["brand", "voice", "global"],
    visibility: Visibility.GLOBAL,
    createdById: "user-trung",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(15),
  },
  {
    id: "mem-2",
    organizationId: "org-1",
    workspaceId: "ws-bros",
    type: MemoryType.INSTRUCTION,
    title: "Bros Photo Listing Description SOP",
    content: "All listing descriptions must: 1) Open with neighborhood context, 2) Highlight top 3 features, 3) Include square footage and bed/bath count naturally, 4) End with a lifestyle hook. Target: 200-300 words. Avoid superlatives like 'best' or 'amazing'.",
    tags: ["sop", "listing", "content"],
    visibility: Visibility.WORKSPACE,
    createdById: "user-trung",
    createdAt: daysAgo(55),
    updatedAt: daysAgo(10),
  },
  {
    id: "mem-3",
    organizationId: "org-1",
    workspaceId: "ws-luxe",
    type: MemoryType.CONTEXT,
    title: "Luxe Realty Brand Context",
    content: "Luxe Realty Group targets the high-end Houston market ($800K+). Their brand is aspirational but approachable. Key neighborhoods: River Oaks, West University, Memorial. Agents: 12 licensed realtors. Primary competitor: Compass Houston.",
    tags: ["brand", "context", "luxe"],
    visibility: Visibility.WORKSPACE,
    createdById: "user-jessica",
    createdAt: daysAgo(25),
    updatedAt: daysAgo(10),
  },
  {
    id: "mem-4",
    organizationId: "org-1",
    type: MemoryType.PREFERENCE,
    title: "Trung's Agent Naming Convention",
    content: "All agent names should be single words, lowercase in slugs, evocative of their function. Examples: Scribe (writer), Pixel (media), Ledger (finance), Sentinel (monitor). Avoid generic names like 'Assistant' or 'Helper'.",
    tags: ["naming", "agents", "preference"],
    visibility: Visibility.GLOBAL,
    createdById: "user-trung",
    createdAt: daysAgo(100),
    updatedAt: daysAgo(50),
  },
  {
    id: "mem-5",
    organizationId: "org-1",
    type: MemoryType.FACT,
    title: "Cost Optimization Thresholds",
    content: "Target cost per listing description: <$0.05. Target cost per social post: <$0.03. Weekly ops report budget: <$0.15. If any single task run exceeds $0.20, flag for review.",
    tags: ["cost", "thresholds", "optimization"],
    visibility: Visibility.GLOBAL,
    createdById: "user-trung",
    createdAt: daysAgo(60),
    updatedAt: daysAgo(20),
  },
  {
    id: "mem-6",
    organizationId: "org-1",
    workspaceId: "ws-bros",
    type: MemoryType.NOTE,
    title: "Bros Photo Client Preferences",
    content: "Client prefers warm, inviting tone over clinical. They want 'home' not 'property'. Always mention the neighborhood by name. They dislike drone-only listings — every set must have front exterior and at least 5 interior shots.",
    tags: ["client", "preferences", "bros-photo"],
    visibility: Visibility.WORKSPACE,
    createdById: "user-derek",
    createdAt: daysAgo(40),
    updatedAt: daysAgo(15),
  },
  {
    id: "mem-7",
    organizationId: "org-1",
    type: MemoryType.INSTRUCTION,
    title: "Approval Escalation Rules",
    content: "Auto-approve: tasks under $0.05 with no client-facing output. Require human approval: any client-facing content, invoice actions over $500, agent configuration changes, and deployment tasks.",
    tags: ["approval", "rules", "escalation"],
    visibility: Visibility.GLOBAL,
    createdById: "user-trung",
    createdAt: daysAgo(80),
    updatedAt: daysAgo(30),
  },
];

// ─── SOP Documents ───────────────────────────────────────────────────────────

export const sopDocuments: SOPDocument[] = [
  {
    id: "sop-1",
    organizationId: "org-1",
    workspaceId: "ws-bros",
    title: "Listing Content Pipeline SOP",
    content: "## Listing Content Pipeline\n\n1. **Intake**: Pixel receives media upload notification\n2. **QA**: Pixel reviews and tags all media assets\n3. **Draft**: Scribe generates listing description using approved template\n4. **Review**: Description submitted for human approval\n5. **Social**: Hype creates platform-specific posts from approved description\n6. **Publish**: Posts scheduled across platforms\n\nSLA: Intake to published in 48 hours.",
    version: 3,
    visibility: Visibility.WORKSPACE,
    createdById: "user-trung",
    createdAt: daysAgo(50),
    updatedAt: daysAgo(8),
  },
  {
    id: "sop-2",
    organizationId: "org-1",
    title: "Agent Onboarding SOP",
    content: "## New Agent Setup\n\n1. Define role, capabilities, and workspace assignment\n2. Configure model/provider and system prompt\n3. Set permissions per workspace\n4. Run 3 test tasks in sandbox mode\n5. Review output quality with workspace owner\n6. Activate and add to monitoring\n\nAll agents must be registered with Sentinel for heartbeat tracking within 1 hour of activation.",
    version: 2,
    visibility: Visibility.GLOBAL,
    createdById: "user-trung",
    createdAt: daysAgo(100),
    updatedAt: daysAgo(30),
  },
];

// ─── Prompt Templates ────────────────────────────────────────────────────────

export const promptTemplates: PromptTemplate[] = [
  {
    id: "pt-1",
    organizationId: "org-1",
    workspaceId: "ws-bros",
    name: "Listing Description Generator",
    description: "Generates MLS-ready listing descriptions for residential properties",
    template: "Write a compelling listing description for the property at {{address}}, {{city}}, {{state}}. The home has {{bedrooms}} bedrooms and {{bathrooms}} bathrooms with {{sqft}} sq ft. Key features: {{features}}. Neighborhood: {{neighborhood}}. Target length: 200-300 words. Tone: warm and inviting. Avoid superlatives.",
    variables: ["address", "city", "state", "bedrooms", "bathrooms", "sqft", "features", "neighborhood"],
    visibility: Visibility.WORKSPACE,
    createdById: "user-trung",
    createdAt: daysAgo(50),
    updatedAt: daysAgo(10),
  },
  {
    id: "pt-2",
    organizationId: "org-1",
    name: "Social Media Caption",
    description: "Creates platform-optimized captions for property posts",
    template: "Create a {{platform}} caption for the listing at {{address}}. Price: {{price}}. Highlight: {{highlight}}. Include a call-to-action. Hashtags: {{hashtags}}. Tone: {{tone}}. Max length: {{maxLength}} characters.",
    variables: ["platform", "address", "price", "highlight", "hashtags", "tone", "maxLength"],
    visibility: Visibility.GLOBAL,
    createdById: "user-trung",
    createdAt: daysAgo(45),
    updatedAt: daysAgo(12),
  },
];

// ─── Artifacts ───────────────────────────────────────────────────────────────

export const artifacts: Artifact[] = [
  { id: "art-1", taskId: "task-1", agentId: "agent-scribe", workspaceId: "ws-bros", type: ArtifactType.DOCUMENT, name: "Listing Description — 1234 Oak St.md", content: "Nestled in the heart of Houston Heights, this beautifully renovated 4-bedroom, 3-bathroom home at 1234 Oak St offers the perfect blend of historic charm and modern luxury...", mimeType: "text/markdown", createdAt: daysAgo(3) },
  { id: "art-2", taskId: "task-18", agentId: "agent-atlas", workspaceId: "ws-hq", type: ArtifactType.REPORT, name: "Weekly Ops Report — Mar 10-16.pdf", url: "/artifacts/ops-report-mar-10-16.pdf", mimeType: "application/pdf", sizeBytes: 245000, createdAt: daysAgo(4) },
  { id: "art-3", taskId: "task-11", agentId: "agent-compass", workspaceId: "ws-luxe", type: ArtifactType.SPREADSHEET, name: "Q1 Social Calendar Audit.xlsx", url: "/artifacts/q1-social-audit.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sizeBytes: 89000, createdAt: daysAgo(7) },
  { id: "art-4", taskId: "task-16", agentId: "agent-quill", workspaceId: "ws-hq", type: ArtifactType.DRAFT, name: "Landing Page Headlines — 3 Variants.md", content: "**Variant A:** Your AI Workforce, Ready to Deploy\n**Variant B:** Run Your Business with Intelligent Agents\n**Variant C:** The Operating System for AI-Powered Teams", mimeType: "text/markdown", createdAt: daysAgo(2) },
];

// ─── Integrations ────────────────────────────────────────────────────────────

export const integrations: Integration[] = [
  { id: "int-1", organizationId: "org-1", type: IntegrationType.STRIPE, name: "Stripe Payments", status: IntegrationStatus.ACTIVE, config: { webhookEndpoint: "/api/webhooks/stripe", liveMode: true }, lastSyncAt: hoursAgo(1), createdAt: daysAgo(100), updatedAt: daysAgo(4) },
  { id: "int-2", organizationId: "org-1", workspaceId: "ws-bros", type: IntegrationType.GOOGLE_DRIVE, name: "Bros Photo Drive", status: IntegrationStatus.ACTIVE, config: { folderId: "1a2b3c4d5e", syncDirection: "bidirectional" }, lastSyncAt: hoursAgo(2), createdAt: daysAgo(55), updatedAt: daysAgo(5) },
  { id: "int-3", organizationId: "org-1", workspaceId: "ws-luxe", type: IntegrationType.META_FACEBOOK, name: "Luxe Realty Meta", status: IntegrationStatus.ACTIVE, config: { pageId: "luxerealtygroup", permissions: ["pages_manage_posts", "pages_read_engagement"] }, lastSyncAt: hoursAgo(6), createdAt: daysAgo(25), updatedAt: daysAgo(3) },
  { id: "int-4", organizationId: "org-1", workspaceId: "ws-bros", type: IntegrationType.GOOGLE_SHEETS, name: "Bros Photo Listings Tracker", status: IntegrationStatus.ACTIVE, config: { spreadsheetId: "abc123xyz", sheetName: "Active Listings" }, lastSyncAt: hoursAgo(4), createdAt: daysAgo(50), updatedAt: daysAgo(2) },
  { id: "int-5", organizationId: "org-1", type: IntegrationType.WEBHOOK, name: "Slack Notifications", status: IntegrationStatus.ACTIVE, config: { webhookUrl: "https://hooks.slack.com/services/T00/B00/xxx", channels: ["#ops-alerts", "#agent-activity"] }, lastSyncAt: minutesAgo(5), createdAt: daysAgo(90), updatedAt: daysAgo(1) },
];

// ─── Cost Records ────────────────────────────────────────────────────────────

export const costRecords: CostRecord[] = [
  // Scribe — content generation
  { id: "cost-1", organizationId: "org-1", workspaceId: "ws-bros", agentId: "agent-scribe", taskRunId: "run-1", model: "claude-sonnet-4-20250514", provider: "anthropic", inputTokens: 1820, outputTokens: 890, costUsd: 0.042, recordedAt: daysAgo(3) },
  { id: "cost-2", organizationId: "org-1", workspaceId: "ws-bros", agentId: "agent-scribe", model: "claude-sonnet-4-20250514", provider: "anthropic", inputTokens: 1450, outputTokens: 720, costUsd: 0.034, recordedAt: daysAgo(5) },
  { id: "cost-3", organizationId: "org-1", workspaceId: "ws-bros", agentId: "agent-scribe", model: "claude-sonnet-4-20250514", provider: "anthropic", inputTokens: 2100, outputTokens: 950, costUsd: 0.048, recordedAt: daysAgo(8) },
  // Pixel — media processing
  { id: "cost-4", organizationId: "org-1", workspaceId: "ws-bros", agentId: "agent-pixel", taskRunId: "run-2", model: "gpt-4o-mini", provider: "openai", inputTokens: 450, outputTokens: 320, costUsd: 0.008, recordedAt: daysAgo(4) },
  { id: "cost-5", organizationId: "org-1", workspaceId: "ws-bros", agentId: "agent-pixel", model: "gpt-4o-mini", provider: "openai", inputTokens: 380, outputTokens: 280, costUsd: 0.006, recordedAt: daysAgo(7) },
  // Muse — client ops (failed)
  { id: "cost-6", organizationId: "org-1", workspaceId: "ws-bros", agentId: "agent-muse", taskRunId: "run-3", model: "gpt-4o-mini", provider: "openai", inputTokens: 680, outputTokens: 240, costUsd: 0.009, recordedAt: hoursAgo(8) },
  // Compass — strategy
  { id: "cost-7", organizationId: "org-1", workspaceId: "ws-luxe", agentId: "agent-compass", taskRunId: "run-4", model: "claude-sonnet-4-20250514", provider: "anthropic", inputTokens: 3200, outputTokens: 1450, costUsd: 0.072, recordedAt: daysAgo(7) },
  // Radar — lead scoring
  { id: "cost-8", organizationId: "org-1", workspaceId: "ws-luxe", agentId: "agent-radar", taskRunId: "run-5", model: "gpt-4o-mini", provider: "openai", inputTokens: 2100, outputTokens: 380, costUsd: 0.025, recordedAt: daysAgo(18) },
  { id: "cost-9", organizationId: "org-1", workspaceId: "ws-luxe", agentId: "agent-radar", model: "gpt-4o-mini", provider: "openai", inputTokens: 1800, outputTokens: 420, costUsd: 0.022, recordedAt: daysAgo(4) },
  // Forge — engineering
  { id: "cost-10", organizationId: "org-1", workspaceId: "ws-hq", agentId: "agent-forge", taskRunId: "run-6", model: "claude-sonnet-4-20250514", provider: "anthropic", inputTokens: 4500, outputTokens: 1200, costUsd: 0.089, recordedAt: daysAgo(4) },
  { id: "cost-11", organizationId: "org-1", workspaceId: "ws-hq", agentId: "agent-forge", model: "claude-sonnet-4-20250514", provider: "anthropic", inputTokens: 3800, outputTokens: 980, costUsd: 0.074, recordedAt: daysAgo(9) },
  // Atlas — reporting
  { id: "cost-12", organizationId: "org-1", workspaceId: "ws-hq", agentId: "agent-atlas", taskRunId: "run-7", model: "gpt-4o", provider: "openai", inputTokens: 5800, outputTokens: 2100, costUsd: 0.118, recordedAt: daysAgo(4) },
  { id: "cost-13", organizationId: "org-1", workspaceId: "ws-hq", agentId: "agent-atlas", model: "gpt-4o", provider: "openai", inputTokens: 4200, outputTokens: 1800, costUsd: 0.092, recordedAt: daysAgo(11) },
  // Echo — social media
  { id: "cost-14", organizationId: "org-1", workspaceId: "ws-luxe", agentId: "agent-echo", taskRunId: "run-10", model: "gpt-4o", provider: "openai", inputTokens: 1200, outputTokens: 580, costUsd: 0.028, recordedAt: daysAgo(6) },
  { id: "cost-15", organizationId: "org-1", workspaceId: "ws-luxe", agentId: "agent-echo", model: "gpt-4o", provider: "openai", inputTokens: 980, outputTokens: 450, costUsd: 0.022, recordedAt: daysAgo(9) },
  { id: "cost-16", organizationId: "org-1", workspaceId: "ws-luxe", agentId: "agent-echo", model: "gpt-4o", provider: "openai", inputTokens: 1100, outputTokens: 520, costUsd: 0.025, recordedAt: daysAgo(12) },
  // Hype — social media (Bros Photo)
  { id: "cost-17", organizationId: "org-1", workspaceId: "ws-bros", agentId: "agent-hype", model: "gpt-4o", provider: "openai", inputTokens: 900, outputTokens: 480, costUsd: 0.021, recordedAt: daysAgo(5) },
  { id: "cost-18", organizationId: "org-1", workspaceId: "ws-bros", agentId: "agent-hype", model: "gpt-4o", provider: "openai", inputTokens: 1050, outputTokens: 550, costUsd: 0.024, recordedAt: daysAgo(10) },
  // Ledger — finance
  { id: "cost-19", organizationId: "org-1", workspaceId: "ws-hq", agentId: "agent-ledger", taskRunId: "run-9", model: "gpt-4o-mini", provider: "openai", inputTokens: 3800, outputTokens: 900, costUsd: 0.047, recordedAt: daysAgo(9) },
  { id: "cost-20", organizationId: "org-1", workspaceId: "ws-hq", agentId: "agent-ledger", model: "gpt-4o-mini", provider: "openai", inputTokens: 2200, outputTokens: 650, costUsd: 0.029, recordedAt: daysAgo(14) },
  // Quill — brand copy
  { id: "cost-21", organizationId: "org-1", workspaceId: "ws-hq", agentId: "agent-quill", model: "gpt-4o", provider: "openai", inputTokens: 1500, outputTokens: 820, costUsd: 0.035, recordedAt: daysAgo(2) },
  // Sentinel — monitoring (low cost)
  { id: "cost-22", organizationId: "org-1", workspaceId: "ws-hq", agentId: "agent-sentinel", model: "gpt-4o-mini", provider: "openai", inputTokens: 200, outputTokens: 80, costUsd: 0.003, recordedAt: minutesAgo(1) },
  { id: "cost-23", organizationId: "org-1", workspaceId: "ws-hq", agentId: "agent-sentinel", model: "gpt-4o-mini", provider: "openai", inputTokens: 200, outputTokens: 85, costUsd: 0.003, recordedAt: hoursAgo(1) },
  // lil_Bin — orchestration
  { id: "cost-24", organizationId: "org-1", agentId: "agent-lil-bin", model: "gpt-4o", provider: "openai", inputTokens: 2800, outputTokens: 1100, costUsd: 0.058, recordedAt: minutesAgo(10) },
  { id: "cost-25", organizationId: "org-1", agentId: "agent-lil-bin", model: "gpt-4o", provider: "openai", inputTokens: 3100, outputTokens: 1250, costUsd: 0.065, recordedAt: daysAgo(1) },
  // Nova — luxury content
  { id: "cost-26", organizationId: "org-1", workspaceId: "ws-bros", agentId: "agent-nova", model: "claude-sonnet-4-20250514", provider: "anthropic", inputTokens: 1900, outputTokens: 880, costUsd: 0.044, recordedAt: daysAgo(2) },
];

// ─── Agent Heartbeats ────────────────────────────────────────────────────────

export const agentHeartbeats: AgentHeartbeat[] = [
  { id: "hb-1", agentId: "agent-lil-bin", status: AgentStatus.BUSY, cpuPercent: 42, memoryMb: 512, activeTaskId: "task-20", timestamp: minutesAgo(2) },
  { id: "hb-2", agentId: "agent-scribe", status: AgentStatus.ONLINE, cpuPercent: 28, memoryMb: 384, activeTaskId: "task-2", timestamp: minutesAgo(15) },
  { id: "hb-3", agentId: "agent-pixel", status: AgentStatus.IDLE, cpuPercent: 5, memoryMb: 256, timestamp: hoursAgo(1) },
  { id: "hb-4", agentId: "agent-hype", status: AgentStatus.ONLINE, cpuPercent: 12, memoryMb: 310, timestamp: minutesAgo(30) },
  { id: "hb-5", agentId: "agent-ledger", status: AgentStatus.ONLINE, cpuPercent: 18, memoryMb: 290, timestamp: hoursAgo(2) },
  { id: "hb-6", agentId: "agent-echo", status: AgentStatus.BUSY, cpuPercent: 55, memoryMb: 480, activeTaskId: "task-9", timestamp: minutesAgo(5) },
  { id: "hb-7", agentId: "agent-atlas", status: AgentStatus.ONLINE, cpuPercent: 35, memoryMb: 420, activeTaskId: "task-19", timestamp: hoursAgo(1) },
  { id: "hb-8", agentId: "agent-sentinel", status: AgentStatus.ONLINE, cpuPercent: 8, memoryMb: 180, timestamp: minutesAgo(1) },
  { id: "hb-9", agentId: "agent-forge", status: AgentStatus.PAUSED, cpuPercent: 0, memoryMb: 128, timestamp: hoursAgo(6) },
  { id: "hb-10", agentId: "agent-radar", status: AgentStatus.ONLINE, cpuPercent: 22, memoryMb: 340, activeTaskId: "task-25", timestamp: hoursAgo(3) },
  { id: "hb-11", agentId: "agent-muse", status: AgentStatus.ERROR, cpuPercent: 0, memoryMb: 64, metadata: { lastError: "SMTP connection timeout", errorSince: hoursAgo(8).toISOString() }, timestamp: hoursAgo(8) },
];

// ─── Comments ────────────────────────────────────────────────────────────────

export const comments: Comment[] = [
  { id: "cmt-1", taskId: "task-1", agentId: "agent-scribe", content: "Draft complete — 278 words. Highlighted the renovated kitchen, pool, and Heights walkability. Ready for review.", createdAt: daysAgo(3), updatedAt: daysAgo(3) },
  { id: "cmt-2", taskId: "task-1", userId: "user-derek", content: "Looks great! One note: change 'stunning' to 'beautifully renovated' — client prefers understated language.", createdAt: daysAgo(2), updatedAt: daysAgo(2) },
  { id: "cmt-3", taskId: "task-7", agentId: "agent-muse", content: "Failed to send confirmation email after 3 retries. SMTP provider appears to be rate-limiting our domain.", createdAt: hoursAgo(8), updatedAt: hoursAgo(8) },
  { id: "cmt-4", taskId: "task-7", agentId: "agent-lil-bin", content: "Escalating to Trung — Muse's email provider needs attention. Suggesting we switch to SendGrid as backup.", createdAt: hoursAgo(7), updatedAt: hoursAgo(7) },
  { id: "cmt-5", taskId: "task-8", agentId: "agent-ledger", content: "3 overdue invoices found: INV-2025-0342 ($1,800 — 22 days), INV-2025-0351 ($1,200 — 18 days), INV-2025-0358 ($1,250 — 16 days). Total: $4,250. Awaiting approval to send reminders.", createdAt: hoursAgo(2), updatedAt: hoursAgo(2) },
  { id: "cmt-6", taskId: "task-15", agentId: "agent-forge", content: "Root cause: Stripe SDK was using a 30-second tolerance but our server clock drifts up to 45 seconds. Increased tolerance to 300s and added NTP sync check.", createdAt: daysAgo(4), updatedAt: daysAgo(4) },
  { id: "cmt-7", taskId: "task-12", agentId: "agent-compass", content: "Blocked — need the Meta Ads API integration to be activated before I can pull competitor ad spend data.", createdAt: daysAgo(3), updatedAt: daysAgo(3) },
];

// ─── Module Installations ────────────────────────────────────────────────────

export const moduleInstallations: ModuleInstallation[] = [
  {
    id: "mod-inst-1",
    workspaceId: "ws-bros",
    moduleSlug: "real-estate-content",
    moduleName: "Real Estate Content Suite",
    version: "1.4.2",
    status: ModuleStatus.ACTIVE,
    config: { listingDescriptionTemplate: "pt-1", autoQaEnabled: true, maxPhotosPerListing: 50 },
    installedById: "user-trung",
    installedAt: daysAgo(55),
    updatedAt: daysAgo(8),
  },
  {
    id: "mod-inst-2",
    workspaceId: "ws-luxe",
    moduleSlug: "real-estate-content",
    moduleName: "Real Estate Content Suite",
    version: "1.4.2",
    status: ModuleStatus.ACTIVE,
    config: { listingDescriptionTemplate: "pt-1", autoQaEnabled: false, maxPhotosPerListing: 75 },
    installedById: "user-trung",
    installedAt: daysAgo(25),
    updatedAt: daysAgo(5),
  },
  {
    id: "mod-inst-3",
    workspaceId: "ws-luxe",
    moduleSlug: "social-media-manager",
    moduleName: "Social Media Manager",
    version: "2.1.0",
    status: ModuleStatus.ACTIVE,
    config: { platforms: ["facebook", "instagram", "tiktok"], autoSchedule: true, approvalRequired: true },
    installedById: "user-jessica",
    installedAt: daysAgo(20),
    updatedAt: daysAgo(3),
  },
  {
    id: "mod-inst-4",
    workspaceId: "ws-hq",
    moduleSlug: "invoice-tracker",
    moduleName: "Invoice Tracker",
    version: "1.2.0",
    status: ModuleStatus.ACTIVE,
    config: { overdueThresholdDays: 15, autoReminders: false, stripeIntegrationId: "int-1" },
    installedById: "user-trung",
    installedAt: daysAgo(100),
    updatedAt: daysAgo(4),
  },
];

// ─── Listings ────────────────────────────────────────────────────────────────

export const listings: Listing[] = [
  {
    id: "listing-1",
    workspaceId: "ws-bros",
    address: "1234 Oak St",
    city: "Houston",
    state: "TX",
    zip: "77008",
    mlsNumber: "MLS-98234501",
    price: 625000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2850,
    status: ListingStatus.PUBLISHED,
    agentId: "agent-scribe",
    assignedToUserId: "user-derek",
    description: "Beautifully renovated 4BR/3BA in Houston Heights with chef's kitchen, backyard pool, and original hardwood floors.",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(2),
  },
  {
    id: "listing-2",
    workspaceId: "ws-bros",
    address: "5678 Westheimer Rd #405",
    city: "Houston",
    state: "TX",
    zip: "77056",
    mlsNumber: "MLS-98234612",
    price: 385000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1420,
    status: ListingStatus.CONTENT_DRAFTING,
    agentId: "agent-scribe",
    assignedToUserId: "user-derek",
    description: null as unknown as string,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
  {
    id: "listing-3",
    workspaceId: "ws-bros",
    address: "9012 Memorial Dr",
    city: "Houston",
    state: "TX",
    zip: "77024",
    mlsNumber: "MLS-98234720",
    price: 1250000,
    bedrooms: 5,
    bathrooms: 4,
    sqft: 4200,
    status: ListingStatus.MEDIA_READY,
    agentId: "agent-pixel",
    assignedToUserId: "user-derek",
    notes: "Luxury estate — full drone coverage completed. 42 photos + walkthrough video.",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(4),
  },
  {
    id: "listing-4",
    workspaceId: "ws-bros",
    address: "3456 Montrose Blvd",
    city: "Houston",
    state: "TX",
    zip: "77006",
    mlsNumber: "MLS-98234835",
    price: 475000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1980,
    status: ListingStatus.INTAKE,
    agentId: "agent-pixel",
    notes: "28 photos uploaded, awaiting tagging and organization.",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: "listing-5",
    workspaceId: "ws-bros",
    address: "7890 Yale St",
    city: "Houston",
    state: "TX",
    zip: "77008",
    mlsNumber: "MLS-98234948",
    price: 545000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 2100,
    status: ListingStatus.REVIEW,
    agentId: "agent-scribe",
    assignedToUserId: "user-derek",
    description: "Charming craftsman in Houston Heights featuring original hardwood floors, a wrap-around porch, and a chef's kitchen with custom cabinetry.",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },
  {
    id: "listing-6",
    workspaceId: "ws-bros",
    address: "4500 Kirby Dr #12",
    city: "Houston",
    state: "TX",
    zip: "77098",
    mlsNumber: "MLS-98235061",
    price: 890000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 1100,
    status: ListingStatus.NEW,
    notes: "Luxury high-rise unit — skyline views, concierge service. Awaiting photos.",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "listing-7",
    workspaceId: "ws-luxe",
    address: "2200 River Oaks Blvd",
    city: "Houston",
    state: "TX",
    zip: "77019",
    mlsNumber: "MLS-98235174",
    price: 3450000,
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    status: ListingStatus.PUBLISHED,
    agentId: "agent-echo",
    assignedToUserId: "user-jessica",
    description: "Stunning River Oaks estate with grand circular driveway, chef's kitchen, wine cellar, resort-style pool, and guest quarters.",
    createdAt: daysAgo(15),
    updatedAt: daysAgo(2),
  },
  {
    id: "listing-8",
    workspaceId: "ws-luxe",
    address: "1800 West University Blvd",
    city: "Houston",
    state: "TX",
    zip: "77005",
    mlsNumber: "MLS-98235287",
    price: 1875000,
    bedrooms: 5,
    bathrooms: 5,
    sqft: 5200,
    status: ListingStatus.CONTENT_DRAFTING,
    agentId: "agent-echo",
    assignedToUserId: "user-jessica",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(2),
  },
  {
    id: "listing-9",
    workspaceId: "ws-luxe",
    address: "4100 San Felipe St #2201",
    city: "Houston",
    state: "TX",
    zip: "77027",
    mlsNumber: "MLS-98235390",
    price: 1150000,
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2800,
    status: ListingStatus.PUBLISHED,
    agentId: "agent-echo",
    assignedToUserId: "user-jessica",
    description: "Luxury penthouse in the Tanglewood area with panoramic views, private elevator, and resort-style amenities.",
    createdAt: daysAgo(20),
    updatedAt: daysAgo(5),
  },
  {
    id: "listing-10",
    workspaceId: "ws-bros",
    address: "2345 Heights Blvd",
    city: "Houston",
    state: "TX",
    zip: "77008",
    mlsNumber: "MLS-98235503",
    price: 715000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3100,
    status: ListingStatus.PUBLISHED,
    agentId: "agent-scribe",
    assignedToUserId: "user-derek",
    description: "Modern farmhouse in the Heights with open floor plan, designer finishes, and a landscaped backyard with fire pit.",
    createdAt: daysAgo(18),
    updatedAt: daysAgo(8),
  },
];

// ─── Media Assets ────────────────────────────────────────────────────────────

export const mediaAssets: MediaAsset[] = [
  // Listing 1 — 1234 Oak St
  { id: "media-1", listingId: "listing-1", type: MediaAssetType.FRONT_EXTERIOR, url: "/media/listing-1/front-exterior-01.jpg", fileName: "front-exterior-01.jpg", mimeType: "image/jpeg", sizeBytes: 2400000, sortOrder: 1, createdAt: daysAgo(11) },
  { id: "media-2", listingId: "listing-1", type: MediaAssetType.INTERIOR, url: "/media/listing-1/kitchen-01.jpg", fileName: "kitchen-01.jpg", mimeType: "image/jpeg", sizeBytes: 1800000, sortOrder: 2, createdAt: daysAgo(11) },
  { id: "media-3", listingId: "listing-1", type: MediaAssetType.INTERIOR, url: "/media/listing-1/living-room-01.jpg", fileName: "living-room-01.jpg", mimeType: "image/jpeg", sizeBytes: 2100000, sortOrder: 3, createdAt: daysAgo(11) },
  { id: "media-4", listingId: "listing-1", type: MediaAssetType.BACK_EXTERIOR, url: "/media/listing-1/backyard-pool-01.jpg", fileName: "backyard-pool-01.jpg", mimeType: "image/jpeg", sizeBytes: 2600000, sortOrder: 4, createdAt: daysAgo(11) },
  { id: "media-5", listingId: "listing-1", type: MediaAssetType.DRONE, url: "/media/listing-1/drone-01.jpg", fileName: "drone-01.jpg", mimeType: "image/jpeg", sizeBytes: 3200000, sortOrder: 5, createdAt: daysAgo(11) },
  // Listing 3 — 9012 Memorial Dr
  { id: "media-6", listingId: "listing-3", type: MediaAssetType.DRONE, url: "/media/listing-3/drone-aerial-01.jpg", fileName: "drone-aerial-01.jpg", mimeType: "image/jpeg", sizeBytes: 4100000, sortOrder: 1, createdAt: daysAgo(7) },
  { id: "media-7", listingId: "listing-3", type: MediaAssetType.FRONT_EXTERIOR, url: "/media/listing-3/front-01.jpg", fileName: "front-01.jpg", mimeType: "image/jpeg", sizeBytes: 2800000, sortOrder: 2, createdAt: daysAgo(7) },
  { id: "media-8", listingId: "listing-3", type: MediaAssetType.VIDEO, url: "/media/listing-3/walkthrough.mp4", fileName: "walkthrough.mp4", mimeType: "video/mp4", sizeBytes: 125000000, sortOrder: 3, createdAt: daysAgo(7) },
  // Listing 7 — 2200 River Oaks Blvd
  { id: "media-9", listingId: "listing-7", type: MediaAssetType.FRONT_EXTERIOR, url: "/media/listing-7/front-01.jpg", fileName: "front-01.jpg", mimeType: "image/jpeg", sizeBytes: 3500000, sortOrder: 1, createdAt: daysAgo(14) },
  { id: "media-10", listingId: "listing-7", type: MediaAssetType.INTERIOR, url: "/media/listing-7/wine-cellar-01.jpg", fileName: "wine-cellar-01.jpg", mimeType: "image/jpeg", sizeBytes: 2200000, sortOrder: 2, createdAt: daysAgo(14) },
  { id: "media-11", listingId: "listing-7", type: MediaAssetType.BACK_EXTERIOR, url: "/media/listing-7/pool-area-01.jpg", fileName: "pool-area-01.jpg", mimeType: "image/jpeg", sizeBytes: 2900000, sortOrder: 3, createdAt: daysAgo(14) },
  { id: "media-12", listingId: "listing-7", type: MediaAssetType.DRONE, url: "/media/listing-7/drone-estate-01.jpg", fileName: "drone-estate-01.jpg", mimeType: "image/jpeg", sizeBytes: 4500000, sortOrder: 4, createdAt: daysAgo(14) },
];

// ─── Post Drafts ─────────────────────────────────────────────────────────────

export const postDrafts: PostDraft[] = [
  {
    id: "draft-1",
    workspaceId: "ws-bros",
    listingId: "listing-1",
    platform: PostPlatform.INSTAGRAM,
    status: PostDraftStatus.PUBLISHED,
    caption: "Just listed in Houston Heights! This beautifully renovated 4BR/3BA at 1234 Oak St features a chef's kitchen, sparkling pool, and original hardwood floors. The Heights lifestyle awaits. DM for details!",
    mediaUrls: ["/media/listing-1/front-exterior-01.jpg", "/media/listing-1/kitchen-01.jpg", "/media/listing-1/backyard-pool-01.jpg"],
    hashtags: ["#HoustonHeights", "#HoustonRealEstate", "#JustListed", "#LuxuryLiving", "#HTXHomes"],
    createdByAgentId: "agent-hype",
    reviewedByUserId: "user-derek",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(2),
  },
  {
    id: "draft-2",
    workspaceId: "ws-bros",
    listingId: "listing-1",
    platform: PostPlatform.FACEBOOK_PAGE,
    status: PostDraftStatus.PUBLISHED,
    caption: "New on the market in Houston Heights! 🏡 4 beds • 3 baths • 2,850 sq ft at 1234 Oak St. Renovated kitchen, pool, and that Heights charm you've been looking for. Click the link in bio for the full tour.",
    mediaUrls: ["/media/listing-1/front-exterior-01.jpg", "/media/listing-1/living-room-01.jpg"],
    hashtags: ["#HoustonHeights", "#NewListing", "#HoustonTX"],
    createdByAgentId: "agent-hype",
    reviewedByUserId: "user-derek",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(2),
  },
  {
    id: "draft-3",
    workspaceId: "ws-luxe",
    listingId: "listing-7",
    platform: PostPlatform.FACEBOOK_PAGE,
    status: PostDraftStatus.REVIEW,
    caption: "Experience luxury living at its finest. This magnificent River Oaks estate at 2200 River Oaks Blvd offers 6 bedrooms, 7 bathrooms, a wine cellar, and a resort-style pool. Schedule your private showing today.",
    mediaUrls: ["/media/listing-7/front-01.jpg", "/media/listing-7/wine-cellar-01.jpg", "/media/listing-7/pool-area-01.jpg"],
    hashtags: ["#RiverOaks", "#LuxuryRealEstate", "#HoustonLuxury", "#DreamHome"],
    scheduledAt: daysFromNow(2),
    createdByAgentId: "agent-echo",
    createdAt: daysAgo(2),
    updatedAt: minutesAgo(5),
  },
  {
    id: "draft-4",
    workspaceId: "ws-luxe",
    listingId: "listing-7",
    platform: PostPlatform.INSTAGRAM,
    status: PostDraftStatus.DRAFT,
    caption: "River Oaks perfection. 6BR/7BA • 8,500 sq ft • Wine cellar • Guest quarters. This is more than a home — it's a lifestyle. Link in bio for virtual tour.",
    mediaUrls: ["/media/listing-7/front-01.jpg", "/media/listing-7/drone-estate-01.jpg"],
    hashtags: ["#RiverOaks", "#LuxuryHomes", "#HoustonLuxury", "#RealEstate", "#Mansion"],
    createdByAgentId: "agent-echo",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "draft-5",
    workspaceId: "ws-luxe",
    listingId: "listing-9",
    platform: PostPlatform.FACEBOOK_PAGE,
    status: PostDraftStatus.SCHEDULED,
    caption: "Penthouse living in Tanglewood! 3BR/3BA with panoramic views, a private elevator, and world-class amenities. Offered at $1,150,000. Contact us for a private showing.",
    mediaUrls: [],
    hashtags: ["#Tanglewood", "#PenthouseLiving", "#HoustonLuxury"],
    scheduledAt: daysFromNow(1),
    createdByAgentId: "agent-echo",
    reviewedByUserId: "user-jessica",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: "draft-6",
    workspaceId: "ws-luxe",
    platform: PostPlatform.FACEBOOK_PAGE,
    status: PostDraftStatus.PUBLISHED,
    caption: "Houston Luxury Market Update (Week of Mar 10): Median list price up 3.2% to $1.1M. Active inventory down 8%. Average days on market: 42. The luxury segment remains competitive — reach out to discuss your strategy.",
    mediaUrls: [],
    hashtags: ["#HoustonRealEstate", "#MarketUpdate", "#LuxuryMarket"],
    createdByAgentId: "agent-echo",
    reviewedByUserId: "user-jessica",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(6),
  },
  {
    id: "draft-7",
    workspaceId: "ws-luxe",
    listingId: "listing-7",
    platform: PostPlatform.TIKTOK,
    status: PostDraftStatus.DRAFT,
    caption: "Dream home tour: River Oaks estate edition 🏠✨ Would you live here? #riveroaks #luxuryhome #housetour #dreamhome",
    mediaUrls: [],
    hashtags: ["#riveroaks", "#luxuryhome", "#housetour", "#dreamhome", "#houston"],
    createdByAgentId: "agent-echo",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
];

// ─── Published Posts ─────────────────────────────────────────────────────────

export const publishedPosts: PublishedPost[] = [
  { id: "pub-1", postDraftId: "draft-1", platform: PostPlatform.INSTAGRAM, platformPostId: "ig_18234567890", publishedAt: daysAgo(2), url: "https://instagram.com/p/abc123", impressions: 2840, engagements: 186 },
  { id: "pub-2", postDraftId: "draft-2", platform: PostPlatform.FACEBOOK_PAGE, platformPostId: "fb_9876543210", publishedAt: daysAgo(2), url: "https://facebook.com/brosphoto/posts/9876543210", impressions: 1520, engagements: 94 },
  { id: "pub-3", postDraftId: "draft-6", platform: PostPlatform.FACEBOOK_PAGE, platformPostId: "fb_1122334455", publishedAt: daysAgo(6), url: "https://facebook.com/luxerealtygroup/posts/1122334455", impressions: 1240, engagements: 67 },
];

// ─── Share Tasks ─────────────────────────────────────────────────────────────

export const shareTasks: ShareTask[] = [
  { id: "share-1", postDraftId: "draft-1", platform: PostPlatform.INSTAGRAM, status: ShareTaskStatus.SHARED, sharedAt: daysAgo(2), createdAt: daysAgo(2) },
  { id: "share-2", postDraftId: "draft-2", platform: PostPlatform.FACEBOOK_PAGE, status: ShareTaskStatus.SHARED, sharedAt: daysAgo(2), createdAt: daysAgo(2) },
  { id: "share-3", postDraftId: "draft-6", platform: PostPlatform.FACEBOOK_PAGE, status: ShareTaskStatus.SHARED, sharedAt: daysAgo(6), createdAt: daysAgo(6) },
  { id: "share-4", postDraftId: "draft-5", platform: PostPlatform.FACEBOOK_PAGE, status: ShareTaskStatus.PENDING, createdAt: daysAgo(1) },
  { id: "share-5", postDraftId: "draft-3", platform: PostPlatform.FACEBOOK_PAGE, status: ShareTaskStatus.PENDING, createdAt: daysAgo(1) },
];

// ─── Invoice Snapshots ───────────────────────────────────────────────────────

export const invoiceSnapshots: InvoiceSnapshot[] = [
  {
    id: "inv-1",
    workspaceId: "ws-bros",
    invoiceNumber: "INV-2025-0342",
    clientName: "Remax Heights Office",
    amount: 1800,
    status: InvoiceStatus.OVERDUE,
    issuedAt: daysAgo(30),
    dueDate: daysAgo(22),
    notes: "Photo shoot package — 3 properties, 150+ photos, drone coverage",
    createdAt: daysAgo(30),
    updatedAt: hoursAgo(2),
  },
  {
    id: "inv-2",
    workspaceId: "ws-bros",
    invoiceNumber: "INV-2025-0351",
    clientName: "Greenway Properties",
    amount: 1200,
    status: InvoiceStatus.OVERDUE,
    issuedAt: daysAgo(25),
    dueDate: daysAgo(18),
    notes: "Content writing package — 5 listing descriptions + social media captions",
    createdAt: daysAgo(25),
    updatedAt: hoursAgo(2),
  },
  {
    id: "inv-3",
    workspaceId: "ws-bros",
    invoiceNumber: "INV-2025-0358",
    clientName: "Keller Williams Montrose",
    amount: 1250,
    status: InvoiceStatus.OVERDUE,
    issuedAt: daysAgo(22),
    dueDate: daysAgo(16),
    notes: "Monthly retainer — photo + content for 4 listings",
    createdAt: daysAgo(22),
    updatedAt: hoursAgo(2),
  },
  {
    id: "inv-4",
    workspaceId: "ws-bros",
    invoiceNumber: "INV-2025-0365",
    clientName: "Coldwell Banker Heights",
    amount: 2400,
    status: InvoiceStatus.PAID,
    issuedAt: daysAgo(28),
    dueDate: daysAgo(14),
    paidAt: daysAgo(12),
    stripePaymentId: "pi_3Qx4Y2BkR8Jm5n7p",
    notes: "Premium package — 6 listings with drone + video",
    createdAt: daysAgo(28),
    updatedAt: daysAgo(12),
  },
  {
    id: "inv-5",
    workspaceId: "ws-luxe",
    invoiceNumber: "INV-2025-0371",
    clientName: "Luxe Realty Group",
    amount: 3500,
    status: InvoiceStatus.SENT,
    issuedAt: daysAgo(10),
    dueDate: daysFromNow(4),
    notes: "Monthly retainer — social media management + content creation",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  {
    id: "inv-6",
    workspaceId: "ws-luxe",
    invoiceNumber: "INV-2025-0378",
    clientName: "Luxe Realty Group",
    amount: 5000,
    status: InvoiceStatus.PAID,
    issuedAt: daysAgo(20),
    dueDate: daysAgo(6),
    paidAt: daysAgo(5),
    stripePaymentId: "pi_3Qx8K9BkR8Jm5n7q",
    notes: "Onboarding package — agent setup, integration config, initial campaign",
    createdAt: daysAgo(20),
    updatedAt: daysAgo(5),
  },
  {
    id: "inv-7",
    workspaceId: "ws-bros",
    invoiceNumber: "INV-2025-0385",
    clientName: "Century 21 Midtown",
    amount: 950,
    status: InvoiceStatus.PAID,
    issuedAt: daysAgo(18),
    dueDate: daysAgo(4),
    paidAt: daysAgo(3),
    stripePaymentId: "pi_3QxC3nBkR8Jm5n7r",
    notes: "Single listing — photo shoot + content + social posts",
    createdAt: daysAgo(18),
    updatedAt: daysAgo(3),
  },
  {
    id: "inv-8",
    workspaceId: "ws-hq",
    invoiceNumber: "INV-2025-0392",
    clientName: "Internal — Platform Costs",
    amount: 450,
    status: InvoiceStatus.DRAFT,
    issuedAt: daysAgo(1),
    dueDate: daysFromNow(14),
    notes: "Monthly AI API costs — OpenAI + Anthropic usage for March (estimated)",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
];

// ─── Integration Accounts ────────────────────────────────────────────────────

export const integrationAccounts: IntegrationAccount[] = [
  {
    id: "intacc-1",
    integrationId: "int-3",
    workspaceId: "ws-luxe",
    accountLabel: "Luxe Realty Facebook Page",
    externalAccountId: "page_luxerealtygroup",
    metadata: { pageName: "Luxe Realty Group", followers: 4200 },
    createdAt: daysAgo(25),
    updatedAt: daysAgo(3),
  },
  {
    id: "intacc-2",
    integrationId: "int-2",
    workspaceId: "ws-bros",
    accountLabel: "Bros Photo Google Drive",
    externalAccountId: "drive_brosphoto",
    metadata: { storageUsedGb: 42.5, totalStorageGb: 100 },
    createdAt: daysAgo(55),
    updatedAt: daysAgo(5),
  },
  {
    id: "intacc-3",
    integrationId: "int-1",
    workspaceId: "ws-hq",
    accountLabel: "Trung AI Ops Stripe",
    externalAccountId: "acct_1QxBkR8Jm5n7",
    metadata: { businessName: "Trung AI Ops LLC", country: "US" },
    createdAt: daysAgo(100),
    updatedAt: daysAgo(4),
  },
];
